# https://docs.codecov.io/docs/ignoring-paths
ignore:
  - "types/*"
  - "tests/*"
  - "scripts/*"
  - "patch/*"
  - "images/*"
  - "docs/*"
  - "chart/*"

coverage:
  status:
    project: on
    patch: off