apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cello-cluster-role
  namespace: kube-system
rules:
  - apiGroups: [ "" ]
    resources: [ "nodes", "namespaces", "configmaps", "serviceaccounts" ]
    verbs: [ "get", "watch", "list", "update" ]
  - apiGroups: [ "" ]
    resources:
      - pods
    verbs:
      - get
      - watch
      - list
      - update
      - patch
  - apiGroups: [ "" ]
    resources:
      - events
    verbs:
      - create
      - patch
  - apiGroups: [ "networking.k8s.io" ]
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "get", "watch", "update", "create" ]
  - apiGroups: [ "extensions" ]
    resources:
      - networkpolicies
    verbs:
      - get
      - list
      - watch
  - apiGroups: [ "" ]
    resources:
      - pods/status
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - "pods/eviction"
    verbs:
      - "create"
    attributeRestrictions: null
  - apiGroups: [ "discovery.k8s.io" ]
    resources:
      - endpointslices
    verbs:
      - get
      - list
      - watch
  - apiGroups: [ "" ]
    resources:
      - endpoints
      - services
    verbs:
      - get
      - list
      - watch
  - apiGroups: [ "" ]
    resources:
      - nodes
      - nodes/status
    verbs:
      - patch
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - create
      - get
      - list
      - watch
      - update
  - apiGroups:
      - cilium.io
    resources:
      - ciliumnodes
      - ciliumnodes/status
      - ciliumexternalworkloads
      - ciliumexternalworkloads/status
      - ciliumidentities
      - ciliumidentities/status
      - ciliumendpoints
      - ciliumendpoints/status
      - ciliumnetworkpolicies
      - ciliumnetworkpolicies/status
      - ciliumclusterwidenetworkpolicies
      - ciliumclusterwidenetworkpolicies/status
      - ciliumlocalredirectpolicies
      - ciliumlocalredirectpolicies/status
      - ciliumegressnatpolicies
    verbs:
      - delete
      - deletecollection
      - get
      - list
      - patch
      - create
      - update
      - watch
